/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.2
 * Generated at: 2019-01-15 05:55:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1547159278803L));
    _jspx_dependants.put("jar:file:/D:/FINARTZ/SpringMVC-Ajax-mongoDB/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Project/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153370682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("    <head>\r\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("    <title>JSP Page</title>\r\n");
      out.write("    <style>\r\n");
      out.write("        table, th, td {\r\n");
      out.write("            border: 1px solid black;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("    \r\n");
      out.write("    <style>\r\n");
      out.write("\t/* This stylesheet sets the width of all images to 100%: */\r\n");
      out.write("\timg {\r\n");
      out.write("\t  width: 100%;\r\n");
      out.write("\t}\r\n");
      out.write("\t</style>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://bootswatch.com/readable/bootstrap.min.css\" />\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css\">\r\n");
      out.write("  \t<link rel=\"stylesheet\" href=\"/resources/demos/style.css\">\r\n");
      out.write("  \t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t</head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <h1>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageHeader}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h1>\r\n");
      out.write("    \r\n");
      out.write("    <table id=\"person-list\" class=\"table table-striped table-hover\" style=\"width: 35%\">\r\n");
      out.write("        <tr>\r\n");
      out.write("        <th>ID</th>\r\n");
      out.write("        <th>Name</th>\r\n");
      out.write("        <th>Surname</th>\r\n");
      out.write("        <th>PhoneNumber</th>\r\n");
      out.write("        </tr>\r\n");
      out.write("        \r\n");
      out.write("        ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("  \r\n");
      out.write("        <tr>\r\n");
      out.write("            <td>NEW</td>\r\n");
      out.write("            <td><input type=\"text\" name=\"name\" id=\"name\" placeholder=\"Enter Name\" /></td>\r\n");
      out.write("            <td><input type=\"text\" name=\"surname\" id=\"surname\" placeholder=\"Enter Surname\" /></td>\r\n");
      out.write("            <td><input type=\"text\" name=\"phoneNumber\" id=\"phoneNumber\" placeholder=\"Enter PhoneNumber\" /></td>\r\n");
      out.write("            <td>\r\n");
      out.write("                <input type=\"button\" id=\"add-person\" value=\"Add\" />\r\n");
      out.write("            </td>\r\n");
      out.write("        </tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t</table>\r\n");
      out.write("    <span class=\"otherchecks label label-success\" style=\"display: none;\"> SUCCESS </span>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("<!--********************************************************-->\r\n");
      out.write("\r\n");
      out.write("<!--Delete person modal-->          \r\n");
      out.write("<div style =\"display: none;\" class=\"deleteDialog\" id=\"delete-dialog-form\" title=\"Delete person\">\r\n");
      out.write("  <p class=\"delete message\">  Do you want to delete person!  </p>  \r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- ******************************************************** -->\r\n");
      out.write("\r\n");
      out.write("<!--Edit person modal-->          \r\n");
      out.write("<div style =\"display: none;\" class=\"editDialog\" id=\"edit-dialog-form\" title=\"Edit person details\">\r\n");
      out.write("  <p class=\"validateTips\">All form fields are required!</p>\r\n");
      out.write("  <p style=\"display: none;\" class=\"error_place_class\">Form fields cannot be empty!</p>\r\n");
      out.write("  \r\n");
      out.write("  <form>\r\n");
      out.write("    <fieldset>\r\n");
      out.write("      \r\n");
      out.write("      <label for=\"name\">Name*</label>\r\n");
      out.write("      <input type=\"text\" name=\"name\" id=\"edit_name\" value=\"\" class=\"text ui-widget-content ui-corner-all\">\r\n");
      out.write("      <label for=\"surname\">Surname*</label>\r\n");
      out.write("      <input type=\"text\" name=\"surname\" id=\"edit_surname\" value=\"\" class=\"text ui-widget-content ui-corner-all\">\r\n");
      out.write("      <label for=\"phoneNumber\">PhoneNumber*</label>\r\n");
      out.write("      <input type=\"text\" name=\"phoneNumber\" id=\"edit_phoneNumber\" value=\"\" class=\"text ui-widget-content ui-corner-all\">\r\n");
      out.write("\r\n");
      out.write("      <input type=\"submit\" value=\"Edit\" tabindex=\"-1\" style=\"position:absolute; top:-1000px\">\r\n");
      out.write("    </fieldset>\r\n");
      out.write("  </form>\r\n");
      out.write("</div>\r\n");
      out.write("<!--********************************************************-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.1.1.min.js\"></script>\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-1.12.4.js\"></script>\r\n");
      out.write("<script src=\"https://code.jquery.com/ui/1.12.1/jquery-ui.js\"></script>\r\n");
      out.write("<script src=\"https://code.jquery.com/ui/1.12.1/jquery-ui.js\"></script>\r\n");
      out.write("<script src=\"../lib/jquery-input-mask-phone-number.js\"></script> \r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("    $(document).ready(function() {\r\n");
      out.write("      \r\n");
      out.write("        $(\"#add-person\").click(function(){\r\n");
      out.write("            \r\n");
      out.write("            var name= $(\"#name\").val();\r\n");
      out.write("            var surname = $(\"#surname\").val();\r\n");
      out.write("            var phoneNumber = $(\"#phoneNumber\").val();\r\n");
      out.write("           \r\n");
      out.write("            var data = JSON.stringify({\"name\":name,\"surname\":surname,\"phoneNumber\":phoneNumber});\r\n");
      out.write("           \r\n");
      out.write("            $.ajax({\r\n");
      out.write("            type : \"POST\",\r\n");
      out.write("            url : \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/addPerson\",\r\n");
      out.write("            contentType: \"application/json\",\r\n");
      out.write("            data : data,\r\n");
      out.write("            success: function(data){\r\n");
      out.write("            \r\n");
      out.write("            if(data===\"\"){\r\n");
      out.write("                return;\r\n");
      out.write("            }else{           \r\n");
      out.write("                var html = [];\r\n");
      out.write("                html.push(\r\n");
      out.write("                  '<tr>',\r\n");
      out.write("                  '<td>'+data.id+'</td>',\r\n");
      out.write("                  \r\n");
      out.write("                  '<td class=\"display'+data.id+'\" id=\"displayName'+data.id+'\">'+data.name+'</td>',\r\n");
      out.write("                  '<td class=\"display'+data.id+'\" id=\"displaySurname'+data.id+'\">'+ data.surname+'</td>',\r\n");
      out.write("                  '<td class=\"display'+data.id+'\" id=\"displayPhoneNumber'+data.id+'\">'+ data.phoneNumber+'</td>',\r\n");
      out.write("                  \r\n");
      out.write("                  '<td style=\"display: none;\" class=\"edit'+data.id+'\"> <input type=\"text\" name=\"editName'+data.id+'\" id=\"editName'+data.id+'\" value=\"'+data.name+'\" /></td>',\r\n");
      out.write("                  '<td style=\"display: none;\" class=\"edit'+data.id+'\"> <input type=\"text\" name=\"editSurname'+data.id+'\" id=\"editSurname'+data.id+'\" value=\"'+data.surname+'\" /></td>',\r\n");
      out.write("                  '<td style=\"display: none;\" class=\"edit'+data.id+'\"> <input type=\"text\" name=\"editPhoneNumber'+data.id+'\" id=\"editPhoneNumber'+data.id+'\" value=\"'+data.phoneNumber+'\" /></td>',\r\n");
      out.write("                  \r\n");
      out.write("                  '<td><input type=\"button\" class=\"delete-person\" data-item-id=\"'+data.id+'\" id=\"delete-person'+data.id+'\" value=\"Delete\" /></td>',\r\n");
      out.write("                  '<td> <input type=\"button\" class=\"update-person\" data-item-id=\"'+data.id+'\" id=\"update-person'+data.id+'\" value=\"Update\" /> </td>',\r\n");
      out.write("                  \r\n");
      out.write("                  '<td style=\"display: none;\" class=\"edit'+data.id+'\"> <input type=\"button\"  class=\"update-person\" data-item-id=\"'+data.id+'\" id=\"edit-person'+data.id+'\" value=\"Confirm\" /> </td>',\r\n");
      out.write("                  \r\n");
      out.write("                  '<td id=\"updatecheck'+data.id+'\" style=\"display: none;background-color: greenyellow; color:white;\">OK</td>',\r\n");
      out.write("                  '</tr>'\r\n");
      out.write("                );\r\n");
      out.write("                var a = html.join(\"\");\r\n");
      out.write("                $('#person-list tr:last').before(a);\r\n");
      out.write("                   $(\"#name\").val(\"\");\r\n");
      out.write("                   $(\"#surname\").val(\"\");\r\n");
      out.write("                   $(\"#phoneNumber\").val(\"\");\r\n");
      out.write("                   $(\".otherchecks\").show();\r\n");
      out.write("                   setTimeout(function() { $(\".otherchecks\").hide(); }, 2000);\r\n");
      out.write("                 }\r\n");
      out.write("               }\r\n");
      out.write("            });\r\n");
      out.write("        });\r\n");
      out.write("        \r\n");
      out.write("        $(\"#person-list\").on('click','.update-person',function(){\r\n");
      out.write("        \t \r\n");
      out.write("            var value = $(event.target).val();\r\n");
      out.write("            var id = $(event.target).data('itemId');\r\n");
      out.write("\r\n");
      out.write("            var tdclasshide = \".display\"+id;\r\n");
      out.write("            var editnameid = \"#editName\"+id;\r\n");
      out.write("            var editsurnameid = \"#editSurname\"+id;\r\n");
      out.write("            var editphoneNumberid = \"#editPhoneNumber\"+id;\r\n");
      out.write("         \r\n");
      out.write("            var gelen_name \t=  $(editnameid).val();\r\n");
      out.write("            var gelen_surname\t=  $(editsurnameid).val();\r\n");
      out.write("            var gelen_phoneNumber\t=  $(editphoneNumberid).val();\r\n");
      out.write("            \r\n");
      out.write("            $('#edit_name').val( gelen_name );\r\n");
      out.write("\t      \t$('#edit_surname').val( gelen_surname );\r\n");
      out.write("\t      \t$('#edit_phoneNumber').val( gelen_phoneNumber );\r\n");
      out.write("\t\t\t            \r\n");
      out.write("\r\n");
      out.write("            \r\n");
      out.write("        \t$( \"#edit-dialog-form\" ).dialog({\r\n");
      out.write("\r\n");
      out.write("      \t      height: 300,\r\n");
      out.write("      \t      width: 1000,\r\n");
      out.write("      \t      modal: true,\r\n");
      out.write("\t      \r\n");
      out.write("\t      \t    buttons: {\r\n");
      out.write("\t      \t        \r\n");
      out.write("\t      \t    \tOKKK : function() {\r\n");
      out.write("\t    \t\t    \t  \r\n");
      out.write("\t \t\t    \t var edited_name = $('#edit_name').val();\r\n");
      out.write("\t \t\t    \t var edited_surname =  $('#edit_surname').val();\r\n");
      out.write("\t \t\t    \t var edited_phoneNumber =  $('#edit_phoneNumber').val();\r\n");
      out.write("\t \t\t    \t\r\n");
      out.write("\t \t\t    \tif(edited_name.length == 0 || edited_surname.length == 0 || edited_phoneNumber.length == 0){\r\n");
      out.write("\t \t\t    \t\t $(\".error_place_class\").show();\r\n");
      out.write("\t \t\t    \t }else{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t                var data = JSON.stringify({\"id\":id, \"name\":edited_name, \"surname\":edited_surname, \"phoneNumber\":edited_phoneNumber});\r\n");
      out.write("\t\t\t                $.ajax({\r\n");
      out.write("\t\t\t                   type : \"PUT\",\r\n");
      out.write("\t\t\t                   url : \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/updatePerson\",\r\n");
      out.write("\t\t\t                   contentType: \"application/json\",\r\n");
      out.write("\t\t\t                   data : data,\r\n");
      out.write("\t\t\t                   success: function(data){\r\n");
      out.write("\t\t\t                     $(tdclasshide).show();\r\n");
      out.write("\t\t\t                     \r\n");
      out.write("\t\t\t                     var dispName = \"#displayName\"+id;\r\n");
      out.write("\t\t\t                     var dispSurname = \"#displaySurname\"+id;\r\n");
      out.write("\t\t\t                     var dispPhoneNumber = \"#displayPhoneNumber\"+id;\r\n");
      out.write("\t\t\t                     \r\n");
      out.write("\t\t\t                     $(dispName).text(edited_name);\r\n");
      out.write("\t\t\t                     $(dispSurname).text(edited_surname);\r\n");
      out.write("\t\t\t                     $(dispPhoneNumber).text(edited_phoneNumber);\r\n");
      out.write("\t\t\t                     \r\n");
      out.write("\t\t\t                     var edit_Name = \"#editName\"+id;\r\n");
      out.write("\t\t\t                     var edit_Surname = \"#editSurname\"+id;\r\n");
      out.write("\t\t\t                     var edit_PhoneNumber = \"#editPhoneNumber\"+id;\r\n");
      out.write("\t\t\t                     \r\n");
      out.write("\t\t\t                     $(edit_Name).text(edited_name);\r\n");
      out.write("\t\t\t                     $(edit_Surname).text(edited_surname);\r\n");
      out.write("\t\t\t                     $(edit_PhoneNumber).text(edited_phoneNumber);\r\n");
      out.write("\t\t\t                     \r\n");
      out.write("\t\t\t                     $('#updatecheck'+id).show();\r\n");
      out.write("\t\t\t                     setTimeout(function() { $('#updatecheck'+id).hide(); }, 2000);\r\n");
      out.write("\t\t\t                   }\r\n");
      out.write("\t\t\t                });\r\n");
      out.write("\t\t\t\t \t \t\t         $( this ).dialog( \"close\" );\r\n");
      out.write("\t\t\t\t \t\t   }\r\n");
      out.write("\t\t\t \t\t },\r\n");
      out.write("\t      \t        \r\n");
      out.write("\t \t\t      \tCancel: function() {\r\n");
      out.write("\t      \t          $( this ).dialog( \"close\" );\r\n");
      out.write("\t      \t        }\r\n");
      out.write("\t      \t      }\r\n");
      out.write("      \t\t    \r\n");
      out.write("      \t\t});\r\n");
      out.write("           \r\n");
      out.write("        });\r\n");
      out.write("        $(\"#person-list\").on('click','.delete-person',function(event){\r\n");
      out.write("            var id = $(event.target).data('itemId');\r\n");
      out.write("            var data = JSON.stringify({\"id\":id});\r\n");
      out.write("            var rowId= \"#\"+event.target.id;\r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("        \t$( \"#delete-dialog-form\" ).dialog({\r\n");
      out.write("    \t      height: 300,\r\n");
      out.write("    \t      width: 1000,\r\n");
      out.write("    \t      modal: true,\r\n");
      out.write("    \t      \r\n");
      out.write("\t      \t    buttons: {\r\n");
      out.write("\t      \t        \r\n");
      out.write("\t      \t    \tOKKK : function() {\r\n");
      out.write("\r\n");
      out.write("\t      \t            $.ajax({\r\n");
      out.write("\t      \t              type : \"DELETE\",\r\n");
      out.write("\t      \t              url : \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/deletePerson\",\r\n");
      out.write("\t      \t              contentType: \"application/json\",\r\n");
      out.write("\t      \t              data : data,\r\n");
      out.write("\t      \t              success: function(data){\r\n");
      out.write("\t      \t                 $(rowId).closest('tr').remove();\r\n");
      out.write("\t      \t                 $(\".otherchecks\").show();\r\n");
      out.write("\t      \t                 setTimeout(function() { $(\".otherchecks\").hide(); }, 2000);\r\n");
      out.write("\t      \t              \t}\r\n");
      out.write("\t      \t              });\r\n");
      out.write("\t      \t            \r\n");
      out.write("\t      \t          $( this ).dialog( \"close\" );\r\n");
      out.write("\t \t\t      \t},\r\n");
      out.write("\t      \t        \r\n");
      out.write("\t \t\t      \tCancel: function() {\r\n");
      out.write("\t      \t          $( this ).dialog( \"close\" );\r\n");
      out.write("\t      \t        }\r\n");
      out.write("\t      \t      }\r\n");
      out.write("    \t\t    \r\n");
      out.write("    \t\t});\r\n");
      out.write("            \r\n");
      out.write("        });\r\n");
      out.write("        \r\n");
      out.write("        $(\"#testmap\").click(function(){\r\n");
      out.write("           \r\n");
      out.write("           var data = JSON.stringify({question:\"1\",answer:\"2\"});\r\n");
      out.write("          \r\n");
      out.write("            $.ajax({\r\n");
      out.write("            type : \"POST\",\r\n");
      out.write("            url : \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/testmap\",\r\n");
      out.write("            headers: { \r\n");
      out.write("                'Accept': 'application/json',\r\n");
      out.write("                'Content-Type': 'application/json' \r\n");
      out.write("            },\r\n");
      out.write("            data : data,\r\n");
      out.write("            success: function(data){\r\n");
      out.write("               \r\n");
      out.write("            }\r\n");
      out.write("            });\r\n");
      out.write("        });\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("    });\r\n");
      out.write("    \r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/jsp/index.jsp(43,8) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/jsp/index.jsp(43,8) '${persons}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${persons}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/jsp/index.jsp(43,8) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("person");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("            <tr>\r\n");
            out.write("                <td> ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${person.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("               \r\n");
            out.write("                <td class=\"display");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${person.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"  id=\"displayName");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${person.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write('>');
            out.write(' ');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${person.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("                <td class=\"display");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${person.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"  id=\"displaySurname");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${person.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write('>');
            out.write(' ');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${person.surname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("                <td class=\"display");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${person.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"  id=\"displayPhoneNumber");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${person.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write('>');
            out.write(' ');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${person.phoneNumber}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("               \r\n");
            out.write("                <td  style=\"display: none;\" class=\"edit");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${person.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"> \r\n");
            out.write("                  <input type=\"text\" name=\"editName");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${person.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" id=\"editName");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${person.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${person.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" />\r\n");
            out.write("                </td>\r\n");
            out.write("                \r\n");
            out.write("                <td style=\"display: none;\" class=\"edit");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${person.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"> \r\n");
            out.write("                  <input type=\"text\" name=\"editSurname");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${person.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" id=\"editSurname");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${person.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${person.surname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" />\r\n");
            out.write("                </td>\r\n");
            out.write("                \r\n");
            out.write("                 <td style=\"display: none;\" class=\"edit");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${person.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"> \r\n");
            out.write("                  <input type=\"text\" name=\"editPhoneNumber");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${person.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" id=\"editPhoneNumber");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${person.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${person.phoneNumber}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" />\r\n");
            out.write("                </td>\r\n");
            out.write("                \r\n");
            out.write("                <td>\r\n");
            out.write("                  <input type=\"button\" class=\"delete-person\" data-item-id=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${person.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" id=\"delete-person");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${person.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" value=\"Delete\" /> \r\n");
            out.write("                </td>\r\n");
            out.write("                \r\n");
            out.write("                <td> \r\n");
            out.write("                  <input type=\"button\" class=\"update-person\" data-item-id=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${person.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" id=\"update-person");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${person.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" value=\"Update\" /> \r\n");
            out.write("                </td>\r\n");
            out.write("                \r\n");
            out.write("                <td style=\"display: none;\" class=\"edit");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${person.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\r\n");
            out.write("                  <input type=\"button\"  class=\"update-person\" data-item-id=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${person.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" id=\"edit-person");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${person.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" value=\"Confirm\" /> \r\n");
            out.write("                </td>\r\n");
            out.write("                \r\n");
            out.write("                <td id=\"updatecheck");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${person.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" style=\"display: none\"><span class=\"label label-success\" >OK</span></td>\r\n");
            out.write("            </tr>\r\n");
            out.write("        ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
